name: pcts
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.1.2
  marquee_widget: ^1.2.0
  http: ^0.13.4
  shared_preferences: ^2.0.11
  encrypted_shared_preferences: ^3.0.1
  syncfusion_flutter_datepicker: ^19.4.41
  progress_dialog: ^1.2.4
  flutter_easyloading: ^3.0.3
  photo_view: ^0.13.0
  uuid: ^3.0.6
  package_info_plus: ^1.0.6
  platform_device_id: ^1.0.1
  url_launcher: ^6.0.18
  device_information: ^0.0.4
  #sms_autofill: ^2.2.0
  crypto: ^3.0.1
  pin_code_fields: ^7.3.0
  loading_animations: ^2.1.0
  dotted_border: ^2.0.0
  flutter_ripple: ^0.0.3
  ext_video_player: ^0.1.2
  flick_video_player: ^0.4.0-dev.4
  webview_flutter: ^3.0.4
  #mp_chart: ^0.3.1
  fl_chart: ^0.45.1
  syncfusion_flutter_charts: ^19.4.41
  flutter_cached_pdfview: ^0.4.1
  expandable: ^5.0.1
  connectivity_plus: ^2.2.1
  #Location & GPS
  geocoding: ^2.0.4
  geolocator: ^8.2.0
  location: ^4.2.0
  permission_handler: ^9.0.1
  pie_chart: ^5.1.0
  #SHOW IMAGE
  cached_network_image: ^3.2.0
  #call
  flutter_phone_direct_caller: ^2.1.1
  google_maps_flutter: ^2.2.1
  dropdown_button2: ^1.9.1
  flutter_launcher_icons: ^0.11.0
  device_info_plus: ^8.0.0
  flutter_tts: ^3.6.3
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "Images/launcher/pctslogo.jpg"
  image_path_android: "Images/launcher/pctslogo.jpg"

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - Images/

